# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: uname -a
      - run: docker build -t gkaskonas/nextcloud:24.0.2 .
      - run: docker push gkaskonas/nextcloud:24.0.2

workflows:
  build:
    jobs:
      - build-medium
